# Generated by Django 5.0.14 on 2026-05-01 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Device name', max_length=100)),
                ('token', models.CharField(db_index=True, help_text='WebSocket authentication token', max_length=64, unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address of ESP8266', max_length=17, null=True, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last connection time', null=True)),
                ('firmware_version', models.CharField(blank=True, default='', help_text='Current firmware version', max_length=20)),
                ('lcd_enabled', models.BooleanField(default=True, help_text='Enable/disable LCD display')),
                ('lcd_rotation_interval', models.IntegerField(default=5, help_text='LCD screen rotation interval in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'last_seen'], name='devices_dev_status_b6dd78_idx')],
            },
        ),
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='Semantic version (e.g., 1.0.0)', max_length=20, unique=True)),
                ('description', models.TextField(help_text='Release notes and changes')),
                ('firmware_file', models.FileField(help_text='Firmware binary file (.bin)', upload_to='firmware/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('checksum', models.CharField(help_text='MD5/SHA256 checksum for integrity', max_length=64)),
                ('is_stable', models.BooleanField(default=True, help_text='Stable release')),
                ('is_latest', models.BooleanField(default=False, help_text='Latest version available')),
                ('min_compatible_version', models.CharField(blank=True, help_text='Minimum compatible version for upgrade', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['version'], name='devices_fir_version_e8dda7_idx'), models.Index(fields=['is_latest', 'is_stable'], name='devices_fir_is_late_01a061_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voltage', models.DecimalField(decimal_places=2, help_text='Voltage in V', max_digits=6)),
                ('current', models.DecimalField(decimal_places=3, help_text='Current in A', max_digits=8)),
                ('power', models.DecimalField(decimal_places=2, help_text='Active power in W', max_digits=10)),
                ('energy', models.DecimalField(decimal_places=3, help_text='Energy consumption in kWh', max_digits=12)),
                ('frequency', models.DecimalField(decimal_places=2, help_text='Frequency in Hz', max_digits=5)),
                ('power_factor', models.DecimalField(decimal_places=3, help_text='Power factor (0-1)', max_digits=4)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Reading timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='devices_ene_device__d2fb4e_idx'), models.Index(fields=['timestamp'], name='devices_ene_timesta_c33322_idx')],
                'unique_together': {('device', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='OTAUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('installing', 'Installing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('progress', models.IntegerField(default=0, help_text='Update progress percentage (0-100)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When device started downloading', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When update completed', null=True)),
                ('previous_version', models.CharField(blank=True, help_text='Version before update', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_updates', to='devices.device')),
                ('firmware_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='devices.firmwareversion')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['device', '-initiated_at'], name='devices_ota_device__cc178d_idx'), models.Index(fields=['status'], name='devices_ota_status_3d8f32_idx')],
            },
        ),
        migrations.CreateModel(
            name='RateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, help_text='Rate per kWh in PHP', max_digits=8)),
                ('name', models.CharField(help_text="Rate name (e.g., 'Peak Hours', 'Off-Peak')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Rate description')),
                ('start_time', models.TimeField(blank=True, help_text='Start time for time-based rates', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for time-based rates', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active rate configuration')),
                ('is_default', models.BooleanField(default=False, help_text='Default rate for device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='devices.device')),
            ],
            options={
                'ordering': ['-is_default', '-is_active', '-created_at'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='devices_rat_device__09e195_idx')],
            },
        ),
    ]
