# Generated by Django 5.0.14 on 2026-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, db_index=True, help_text='WebSocket authentication token', max_length=64, unique=True),
        ),
    ]
