# Generated by Django 5.0.14 on 2026-05-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lcd_templates',
            field=models.JSONField(blank=True, default=list, help_text="Array of LCD screen templates. Example: [{'line1':'{v}V {i}A', 'line2': '{p}W'}]"),
        ),
    ]
