# Generated by Django 5.0.14 on 2026-05-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_lcd_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='nominal_voltage',
            field=models.FloatField(default=230.0, help_text='Nominal mains voltage for this location (V). Used for stability thresholds (±10%).'),
        ),
    ]
